### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by EdisonSu768** [stianeikeland/node-etcd#47]
HI,all
I hav got this error when I boot my application and details more like this,

privatecloud_1     | /server/node_modules/node-etcd/node_modules/deasync/node_modules/bindings/bindings.js:91
privatecloud_1     |   throw err
privatecloud_1     |         ^
privatecloud_1     | Error: Could not locate the bindings file. Tried:
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/build/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/build/Debug/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/build/Release/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/out/Debug/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/Debug/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/out/Release/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/Release/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/build/default/deasync.node
privatecloud_1     |  → /server/node_modules/node-etcd/node_modules/deasync/compiled/2.5.0/linux/x64/deasync.node
privatecloud_1     |   at bindings (/server/node_modules/node-etcd/node_modules/deasync/node_modules/bindings/bindings.js:88:9)
privatecloud_1     |   at Object.<anonymous> (/server/node_modules/node-etcd/node_modules/deasync/index.js:23:31)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.Module._extensions..js (module.js:448:10)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/node_modules/node-etcd/lib/client.js:7:11)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.Module._extensions..js (module.js:448:10)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/node_modules/node-etcd/lib/index.js:9:10)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.Module._extensions..js (module.js:448:10)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/common/etcd.coffee:1:8)
privatecloud_1     |   at Object.<anonymous> (/server/common/etcd.coffee:1:1)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.loadFile (/server/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/update-server.coffee:19:10)
privatecloud_1     |   at Object.<anonymous> (/server/update-server.coffee:1:1)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.loadFile (/server/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/app.coffee:3:10)
privatecloud_1     |   at Object.<anonymous> (/server/app.coffee:1:1)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.loadFile (/server/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
privatecloud_1     |   at Module.load (/server/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Module.require (module.js:365:17)
privatecloud_1     |   at require (module.js:384:17)
privatecloud_1     |   at Object.<anonymous> (/server/index.js:3:1)
privatecloud_1     |   at Module._compile (module.js:430:26)
privatecloud_1     |   at Object.Module._extensions..js (module.js:448:10)
privatecloud_1     |   at Module.load (module.js:355:32)
privatecloud_1     |   at Function.Module._load (module.js:310:12)
privatecloud_1     |   at Function.Module.runMain (module.js:471:10)
privatecloud_1     |   at startup (node.js:117:18)
privatecloud_1     |   at node.js:953:3

how is this going ?  I can not find the files which in node_modules/node-etcd/node_modules/deasync/build/ AND where are them ?

PS: I used Mac OX EI Captian

**Comment by stianeikeland** [comment]
Hello,
is this still a problem?
What nodejs version are you using?

**Comment by EdisonSu768** [comment]
yes, the version is v 2.5.0

and there are more detail, im using Mac OSX EI and i use docer compose to boot my app

and the image of my docker is build on Ubuntu

**Comment by EdisonSu768** [comment]
Hi,

the version is 2.5.0

and i'v used docker compose to boot my app

the host is Mac OSX EI , the image is build on Ubuntu


On Mon, Dec 28, 2015 at 6:52 AM, Stian Eikeland <notifications@github.com>
wrote:

> Hello,
> is this still a problem?
> What nodejs version are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stianeikeland/node-etcd/issues/47#issuecomment-167446371>
> .
>



-- 
Best Regards
*Edison Su *| Trantect Developer
Tel: 13770667129
Mail: edison.su@trantect.com
Web: www.trantect.com
Add: 南京市玄武区黄埔路2号黄埔大厦19楼CD座

**Comment by snackycracky** [comment]
+1

**Comment by stianeikeland** [comment]
Could you try out node-etcd v5.0.2? @trystanj thinks #58 could fix this issue.
