### ISSUE TITLE
Error: Received unexpected response

### ISSUE THREAD

**Issue by shenshouer** [stianeikeland/node-etcd#53]
I got the error with "node-etcd": "^4.1.0":

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Received unexpected response
    at Watcher._unexpectedData (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/watcher.js:75:13)
    at Watcher._unexpectedData (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/watcher.js:3:57)
    at Watcher._respHandler (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/watcher.js:102:19)
    at /Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/watcher.js:3:57
    at Client._handleResponse (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/client.js:223:14)
    at Request._callback (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/lib/client.js:136:22)
    at Request.self.callback (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/goyoo/workspace/vagrant/all/sse/yun-engine/node_modules/node-etcd/node_modules/request/request.js:1057:14)

Process finished with exit code 1
```

**Comment by shenshouer** [comment]
sorry for my error host config.
