### ISSUE TITLE
[BUG] Cannot Set Property Dir of Undefined

### ISSUE THREAD

**Issue by DerekTBrown** [stianeikeland/node-etcd#56]
I have the following line in my code:
``` etcd.mkdir(etcd_dir); ```

if I execute it, I receive the following error:

```/home/dbrown/projects/LearnLinux/redbird/node_modules/node-etcd/lib/index.js:104
    options.dir = true;
                ^

TypeError: Cannot set property 'dir' of undefined
    at Etcd.mkdir (/home/dbrown/projects/LearnLinux/redbird/node_modules/node-etcd/lib/index.js:104:17)
    at /home/dbrown/projects/LearnLinux/redbird/lib/etcd-backend.js:26:12
    at Client._handleResponse (/home/dbrown/projects/LearnLinux/redbird/node_modules/node-etcd/lib/client.js:221:14)
    at Request._callback (/home/dbrown/projects/LearnLinux/redbird/node_modules/node-etcd/lib/client.js:136:22)
    at Request.self.callback (/home/dbrown/projects/LearnLinux/redbird/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/dbrown/projects/LearnLinux/redbird/node_modules/request/request.js:1057:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/dbrown/projects/LearnLinux/redbird/node_modules/request/request.js:1003:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```
```
However, if I change the line to ``` etcd.mkdir(etcd_dir,{}); ```, I get no errors at all. Looks like the parameter needs to default to an empty object.

**Comment by stianeikeland** [comment]
Fixed in v5.0.3 - Thank you! :)
