### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by txiaocao** [stianeikeland/node-etcd#64]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.1
npm WARN react-dom@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm ERR! Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! argv "/workstation/bin/node/node-v6.6.0-linux-x64/bin/node" "/workstation/bin/no" "i"
npm ERR! node v6.6.0
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.8 install: node ./build.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.8 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

@node-etcd

**Comment by xpepermint** [comment]
I also have something similar:

```
/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /node_modules/deasync/build/deasync.node
 → /node_modules/deasync/build/Debug/deasync.node
 → /node_modules/deasync/build/Release/deasync.node
 → /node_modules/deasync/out/Debug/deasync.node
 → /node_modules/deasync/Debug/deasync.node
 → /node_modules/deasync/out/Release/deasync.node
 → /node_modules/deasync/Release/deasync.node
 → /node_modules/deasync/build/default/deasync.node
 → /node_modules/deasync/compiled/7.10.0/linux/x64/deasync.node
    at bindings (/node_modules/bindings/bindings.js:88:9)
    at /node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/node_modules/deasync/index.js:76:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by soyaine** [comment]
It seems the deasync depend lower version Python.
You can try `npm install --python=python2.7`.
