### ISSUE TITLE
Broken release: 6.0.0

### ISSUE THREAD

**Issue by shakefu** [stianeikeland/node-etcd#78]
@stianeikeland, please republish: It appears that the 6.0.0 release of node-etcd is broken (perhaps wasn't successfully transpiled first?)

Here's logs showing the issue:

```bash
# Snip snip
  "dependencies": {
    "fs-extra": "^0.24.0",
    "lodash": "^4.0.0",
    "node-etcd": "^6.0.0",
    "nomnom": "^1.8.1"
  }
}
$ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> deasync@0.1.10 install /Users/jacobalheid/github.com/shakefu/jetconfig/node_modules/deasync
> node ./build.js

`darwin-x64-node-8` exists; testing
Binary is fine; exiting
npm notice created a lockfile as package-lock.json. You should commit this file.
added 130 packages in 4.386s
$ node
> require('node-etcd')
Error: Cannot find module 'node-etcd'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
> 
$ ls node_modules/node-etcd/
LICENSE        README.md      brille.coffee  package.json   src/           test/
```

**Comment by stianeikeland** [comment]
Hey, thanks!

Could you try again now? Released as `node-etcd@beta` (v.6.0.2)

**Comment by shakefu** [comment]
Works! Thanks for the quick turn-around. 👍
